#!/usr/bin/env python3

import os
import fnmatch

# builders
Py_2_NB = Builder(
    action = Action(["jupytext --to ipynb --from py:percent  $SOURCE"]),
    src_suffix = ".py",
    suffix = ".ipynb")

# environment
env = Environment(ENV = {'PATH' : os.environ['PATH'] },
                  platform = 'posix',
                  SrcDir   = ".",
                  Out_Dir  = ".",
                  BUILDERS = { "Python":Py_2_NB },
                  )

env.Depends('final_proj_recommendations.ipynb', 'final_proj_recommendations.py')
env.Depends('final_proj_abtest.ipynb', 'final_proj_abtest.py')

Notebooks = ['final_proj_recommendations.ipynb', 'final_proj_abtest.ipynb']

env.Default(Notebooks)

env.Python(source='final_proj_recommendations.py')
env.Python(source='final_proj_abtest.py')
